# Generated by Django 4.2.23 on 2025-08-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemApps",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("app_name", models.CharField(max_length=64, unique=True)),
                ("label", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="UserGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("group_name", models.CharField(max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("apps", models.ManyToManyField(blank=True, related_name="user_groups", to="accounts.systemapps")),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("account", models.CharField(max_length=64, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("keep_expiration_days", models.IntegerField(default=1)),
                ("first_name", models.CharField(blank=True, max_length=64, null=True)),
                ("last_name", models.CharField(blank=True, max_length=64, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("profile_picture_file_name", models.CharField(blank=True, max_length=128, null=True)),
                ("description", models.TextField(blank=True, max_length=50, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("user_groups", models.ManyToManyField(blank=True, related_name="users", to="accounts.usergroup")),
            ],
        ),
    ]
