"""
Django settings for app_server project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

from .utils.config import load_settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-(r*8*ks!*0b13gbw#ssvno1o4sb!_$s+^1vl6kgru)(74&@iod"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

USE_AUTHENTICATION = True

ALLOWED_HOSTS = ["*"]  # FIXME: For development only, restrict in production

# Application definition

INSTALLED_APPS = [
    # "daphne",  # ASGI server. If use manage.py runserver to run, uncomment this line.
    "django.contrib.auth",  # 使用者與權限系統
    "django.contrib.contenttypes",  # content type framework
    "django.contrib.sessions",  # session 管理
    "rest_framework",
    "rest_framework.authtoken",
    "drf_spectacular",
    "corsheaders",
    "channels",
    "django_celery_beat",
    "accounts",
    "user_registration",
    "alarm_logs",
    "activity_logs",
    "system",
]

ASGI_APPLICATION = "app_server.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
        # "BACKEND": "channels_redis.core.RedisChannelLayer",
        # "CONFIG": {
        #     "hosts": [("127.0.0.1", 6379)],
        # },
    }
}

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "accounts.utils.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": ["accounts.utils.authentication.Permission"],
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 100,
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "FaceRecoSystem API",
    "DESCRIPTION": (
        "This project is a web-based system built on FaceRecognition, "
        "designed to integrate and extend the capabilities of the original FaceRecognition project. \n\n"
        "For more details, see the GitHub repository: [FaceRecognition](https://github.com/JiangXiu11200/FaceRecognition) \n\n"
    ),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

if not USE_AUTHENTICATION:
    del REST_FRAMEWORK["DEFAULT_PERMISSION_CLASSES"]
    del REST_FRAMEWORK["DEFAULT_AUTHENTICATION_CLASSES"]

with open(BASE_DIR / "ca/private.pem") as f:
    JWT_PRIVATE_KEY = f.read()

with open(BASE_DIR / "ca/public.pem") as f:
    JWT_PUBLIC_KEY = f.read()


MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "activity_logs.middleware.ActivityLogMiddleware",
]

CORS_ALLOW_ALL_ORIGINS = True  # TAG: For development only, restrict in production

# CORS_ALLOWED_ORIGINS = [
#     "http://127.0.0.1:3000",  # React dev server
#     "http://localhost:3000",
# ]

CORS_ALLOW_CREDENTIALS = True


ROOT_URLCONF = "app_server.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "app_server.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

settings = load_settings()
# runtime_check(settings)


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": settings.postgres.name,
        "USER": settings.postgres.user,
        "PASSWORD": settings.postgres.password,
        "HOST": settings.postgres.host,
        "PORT": settings.postgres.port,
    }
}

MINIO = settings.minios3.model_dump()
MICROSERVICE = settings.microservice.model_dump()
CELERY = settings.celery.model_dump()

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Taipei"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# HLS 檔案存放路徑
HLS_OUTPUT_PATH = os.path.join(MEDIA_ROOT, "hls")
SCREENSHOT_OUTPUT_PATH = os.path.join(MEDIA_ROOT, "screenshots")

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Celery use Redis as broker and result backend
CELERY_BROKER_URL = CELERY.get("broker", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = CELERY.get("broker", "redis://localhost:6379/0")

CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

# Optional: Celery timezone settings
CELERY_TIMEZONE = "Asia/Taipei"
CELERY_ENABLE_UTC = False
