[project]
name = "FaceRecoSystem"
version = "0.0.1"
description = ""
readme = "README.md"
requires-python = ">=3.9,<3.10"
dependencies = [
    "celery>=5.5.3",
    "channels>=4.2.2",
    "cryptography>=45.0.5",
    "django>=4.2.23",
    "django-celery-beat>=2.8.1",
    "djangorestframework>=3.16.0",
    "djangorestframework-simplejwt>=5.5.1",
    "flower>=2.0.1",
    "gunicorn>=23.0.0",
    "psycopg2>=2.9.10",
    "redis>=6.2.0",
    "rest-framework-simplejwt>=0.0.2",
    "ruff>=0.12.5",
    "uvicorn>=0.35.0",
]


[tool.ruff]
line-length = 120
target-version = "py39"
extend-exclude = [".git", ".venv", "migrations/"]


[tool.ruff.lint]
select = ["E", "F", "I", "UP"]

[tool.ruff.format]
quote-style = "double"
