
[postgres]
host="facereco-postgres"
port = "5432"
name = "facereco"
user = <USERNAME>
password = <PASSWORD>

[minios3]
enable_ssl = false
ca_path = "ca/ca.pem"
endpoint = "facereco-minio:9000"
external_endpoint = "http://<YOUR_DOMAIN>:3001/minio"
access_key = <MINIO_USER>
secret_key = <MINIO_PASSWORD>
connect_timeout = 3
read_timeout = 3
total_timeout = 3
max_retries = 1
backoff_factor = 0.3
pool_maxsize = 10
pool_block = false

[microservice]
endpoint = "http://<SERVICE_DOMAIN>"
internal_token = ""

[tests]
test_server_url = "http://localhost:8000"

[celery]
broker = "redis://facereco-redis:6379/0"

