# Generated by Django 4.2.23 on 2025-08-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DebugConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("debug", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="RecognitionConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("enable_blink_detection", models.BooleanField(default=True)),
                ("dlib_predictor_path", models.CharField(blank=True, default="", max_length=256, null=True)),
                ("dlib_recognition_model_path", models.CharField(blank=True, default="", max_length=256, null=True)),
                ("face_model", models.CharField(blank=True, default="", max_length=256, null=True)),
                ("minimum_bounding_box_height", models.FloatField(default=0.0)),
                ("minimum_face_detection_score", models.FloatField(default=0.0)),
                ("eyes_detection_brightness_threshold", models.IntegerField(default=0)),
                ("eyes_detection_brightness_value_min", models.IntegerField(default=0)),
                ("eyes_detection_brightness_value_max", models.IntegerField(default=0)),
                ("sensitivity", models.FloatField(default=0.5)),
                ("consecutive_prediction_intervals_frame", models.IntegerField(default=90)),
            ],
        ),
        migrations.CreateModel(
            name="VideoConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rtsp", models.CharField(blank=True, default="", max_length=64)),
                ("web_camera", models.IntegerField(blank=True, null=True)),
                ("image_height", models.IntegerField()),
                ("image_width", models.IntegerField()),
                ("detection_range_start_point_x", models.IntegerField()),
                ("detection_range_start_point_y", models.IntegerField()),
                ("detection_range_end_point_x", models.IntegerField()),
                ("detection_range_end_point_y", models.IntegerField()),
            ],
        ),
    ]
