# Generated by Django 4.2.23 on 2025-08-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlarmLogs",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64)),
                ("s3_object_key", models.CharField(blank=True, max_length=128, null=True)),
                ("acknowledged", models.BooleanField(default=False)),
                (
                    "alarm_type",
                    models.IntegerField(
                        choices=[(1, "Info"), (2, "Warning"), (3, "Critical"), (4, "Error"), (5, "Fatal")], default=1
                    ),
                ),
                ("alarm_message", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
